name: Run Postman Tests with Newman

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ” Repository-ni klonla
        uses: actions/checkout@v4

      - name: ğŸ§° Node.js quraÅŸdÄ±r
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: ğŸ“¦ Newman quraÅŸdÄ±r
        run: npm install -g newman

      - name: ğŸ§ª Postman testlÉ™rini iÅŸÉ™ sal
        run: |
          newman run Restful-booker.postman_collection.json \
            -e envir1.postman_environment.json \
            -r cli,html \
            --reporter-html-export newman/report.html

      - name: ğŸ“¤ HTML reportu GitHub-a artefakt kimi É™lavÉ™ et
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman/report.html
